name: Build and Publish CLI Tool

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Bump version and commit
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        VERSION=$(date +'%Y.%m.%d.%H%M')
        echo "New version: $VERSION"
        sed -i "s|<Version>.*</Version>|<Version>$VERSION</Version>|" FrankTools.Cli/FrankTools.Cli.csproj

        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add FrankTools.Cli/FrankTools.Cli.csproj
        git commit -m "🔖 Bump version to $VERSION" || echo "No changes to commit"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }} HEAD:master

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Pack NuGet tool
      run: dotnet pack FrankTools.Cli/FrankTools.Cli.csproj --configuration Release -o ./nupkg

    - name: Publish to NuGet
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
      run: |
        dotnet nuget push "./nupkg/*.nupkg" \
          --api-key $NUGET_API_KEY \
          --source https://api.nuget.org/v3/index.json
